# Generated by Django 3.1.5 on 2021-04-05 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_shop', '0002_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(default='', upload_to='art_shop/images')),
                ('email', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=100)),
                ('linkdin', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
