# Generated by Django 3.1.5 on 2021-04-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_shop', '0004_auto_20210405_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=30)),
                ('last_name', models.CharField(default='', max_length=30)),
                ('email', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=300)),
                ('contact_tel', models.CharField(default='', max_length=10)),
                ('gender', models.CharField(default='', max_length=20)),
                ('user_type', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
