# Generated by Django 3.1.5 on 2021-04-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_shop', '0005_registration1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='art_date',
            field=models.DateField(default=2019),
        ),
    ]
