# Generated by Django 3.1.5 on 2021-04-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_shop', '0006_auto_20210412_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_id', models.ImageField(default=0, upload_to='')),
                ('artist_email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='registration1',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
