# Generated by Django 3.1.5 on 2021-04-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_shop', '0007_auto_20210412_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddToCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_id', models.IntegerField(default=0)),
                ('user_email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_id', models.IntegerField(default=0)),
                ('user_email', models.EmailField(max_length=100)),
                ('address', models.CharField(default='', max_length=300)),
                ('contact_num', models.IntegerField(default=0)),
                ('payment_type', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='my_art',
            name='artist_email',
            field=models.EmailField(max_length=100),
        ),
    ]
