# Generated by Django 3.2 on 2021-04-29 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_shop', '0012_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration1',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='art_shop/images'),
        ),
    ]
