# Generated by Django 3.2 on 2021-04-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_shop', '0013_registration1_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='artist_email',
            field=models.EmailField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='contact_num',
            field=models.CharField(max_length=100),
        ),
    ]
