# Generated by Django 3.2 on 2021-04-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_shop', '0014_auto_20210429_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(default='pending', max_length=30),
        ),
    ]
