# Generated by Django 3.1.5 on 2021-04-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_name', models.CharField(default='', max_length=100)),
                ('art_descripion', models.CharField(default='', max_length=500)),
                ('art_price', models.IntegerField(default=0)),
                ('art_category', models.CharField(default='', max_length=50)),
                ('art_subcategory', models.CharField(default=0, max_length=50)),
                ('art_date', models.DateField(default=-2000)),
            ],
        ),
    ]
