# Generated by Django 3.2 on 2021-04-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_shop', '0010_artfeedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artfeedback',
            old_name='emai',
            new_name='artist_email',
        ),
        migrations.AddField(
            model_name='artfeedback',
            name='email',
            field=models.EmailField(default='email', max_length=100),
            preserve_default=False,
        ),
    ]
